### ISSUE TITLE
Pairing not working

### ISSUE THREAD

**Issue by jvaclavovic** [hap-java/HAP-Java#113]
Hello, after upgrade to latest version (before this I used version 1.2), pairing stop working. I tryed iOS 12 and iOS 14 and both ended with exception:

org.bouncycastle.crypto.tls.TlsFatalAlert: bad_record_mac(20)
	at io.github.hapjava.server.impl.crypto.ChachaDecoder.decodeCiphertext(ChachaDecoder.java:31) ~[hap-2.0.0-snapshot.jar:na]
	at io.github.hapjava.server.impl.crypto.ChachaDecoder.decodeCiphertext(ChachaDecoder.java:41) ~[hap-2.0.0-snapshot.jar:na]
	at io.github.hapjava.server.impl.pairing.FinalPairHandler.decrypt(FinalPairHandler.java:44) ~[hap-2.0.0-snapshot.jar:na]

**Comment by yfre** [comment]
sounds like a newer bcprov version. 
have you changed anything in pom.xml? please make sure bcprov 1.51 is used

**Comment by jvaclavovic** [comment]
Problem solved, thank you. I use spring-cloud-openfeign and bcprov 1.64 is in its dependencies.
